### ISSUE TITLE
A user must use a template GitHub Repo (they can fork a particular template)

### ISSUE THREAD

**Issue by CANIS-NAU** [DiscoverCCRI/portal_v1#21]

**Comment by CANIS-NAU** [comment]
This should be a separate repo--maybe called DISCOVER Experiment Template Repo--that experimenters are directed to fork. Since Jacob is the current operator, he will be the one to set this up, but we should all review. 

Example projects can then be added as branches and this structure can be explained in the repo README.

**Comment by 17jhagan** [comment]
Each templated project should include a src/main.py (primary execution file) and a field for build commands (if needed).

**Comment by 17jhagan** [comment]
Let's try to use this for the next NTU workshop!

**Comment by cjb873** [comment]
Do we need users to supply a Dockerfile? I do not know what it looks like from the perspective of the stationary nodes and drones, but for the rovers, all the experimenter needs to do is write some Python scripts. It would be easier for both us and the user to just collect the code and generate a Dockerfile for the experiment based on the code and the configuration file generated by the Portal.

**Comment by 17jhagan** [comment]
That's a good point! That was sort of a placeholder since I imagined they would be submitting docker applications. I agree that it would be simpler overall if we can construct dockerfiles for them. Additionally, it would be more secure since we know what's going on when the container is executed. I'll let you know when I get the repo and README cleaned up! Thank you!

**Comment by 17jhagan** [comment]
Hey @cjb873, could you give the template another look? I have removed the dockerfile and updated the readme. Let me know what you think!

**Comment by cjb873** [comment]
@17jhagan I really like the template. I think that it is clean and simple, and should allow users to make new experiments easily. I may go back and refactor the RoverDemo so that it just involves a few scripts and does not make explicit references to Docker so as to not confuse people.

**Comment by 17jhagan** [comment]
This is close to being out of review. Waiting on Cody to update the RoverDemo branch, then I'll move this task to complete.

**Comment by cjb873** [comment]
Refactored the RoverDemo to follow Jacob's template
