### ISSUE TITLE
When email notifications are sent from the Portal, the email address associated with this should be a dedicated DISCOVER email

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#24]
Issue to reflect the "Dedicated DISCOVER Email" in the Portal Issue Tracking document.

I worked to get an Outlook email created for us called "DiscoverCCRI@nau.edu":

- This is documented in the following ServiceNow Tickets: [INC0793140](https://nau.service-now.com/nav_to.do?uri=incident.do?sys_id=e11b8ee21b30a99067a6a603b24bcb3f), [INC0793879](https://nau.service-now.com/nav_to.do?uri=incident.do?sys_id=c066d1271b70e9d067a6a603b24bcb6b)

The issue we are facing with the Outlook email is that we need to enable OAUTH2 to authenticate our connection with the email server in order to send email notifications with "DiscoverCCRI@nau.edu". Here's a potentially helpful guide for enabling OAUTH2 for email authentication in Django: https://abhik-b.medium.com/step-by-step-guide-to-email-social-logins-in-django-5e5436e20591

Since my student email works fine, this issue should not affect any portal user experience in presentations/workshops. If we are unable to get OAUTH2 working, it may be better to find an alternate email service that allows basic authentication through python (django).

**Comment by nhatlinh300401** [comment]
Sent an ticket to NAU-ITS about setting up the Email Authentication for DiscoverCCRI@nau.edu and waiting for response

**Comment by nhatlinh300401** [comment]
Right now  I'm using personal email for the portal
