### ISSUE TITLE
When an experimenter or PI goes to the Resources page, there should be a correct site location tied to the resource

### ISSUE THREAD

**Issue by CANIS-NAU** [DiscoverCCRI/portal_v1#26]

**Comment by nhatlinh300401** [comment]
Hey @17jhagan , is there any a list of resource locations in the team's document? Currently, I'm using the google map URL to identify the resource location and still missing the location URL for Hat Ranch and Navajo Tech.

![image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/3808fd2c-fc71-42c3-828d-92783a6b4631)

**Comment by 17jhagan** [comment]
Hi @nhatlinh300401! No, there is not a list of resource locations, but here are the Google Maps links for the locations you are missing:

- Navajo Tech: https://goo.gl/maps/LQw46PgvxBCbyAvPA?coh=178573&entry=tt
- Hat Ranch: https://goo.gl/maps/Drdb7rn1rXLDWHPQ9?coh=178573&entry=tt

**Comment by nhatlinh300401** [comment]
Hey @17jhagan, thank you for links. I have a question for the option "Others", does that need the Google Maps link?
