### ISSUE TITLE
There needs to be more guidance on the resource definition page

### ISSUE THREAD

**Issue by CANIS-NAU** [DiscoverCCRI/portal_v1#27]
Currently, it is very unclear as to what a user is supposed to do when they click the button that asks them to create a new resource.

**Comment by nhatlinh300401** [comment]
Hi Bailey @BaileyMcCauslin, since you're working on [this issue](https://github.com/DiscoverCCRI/portal_v1/issues/34) about the experiment resource definition, so I assign this task to you.
