### ISSUE TITLE
New Experimenters can click a button called "Run a Test Experiment on DISCOVER" that takes them through a basic end-to-end run of the platform

### ISSUE THREAD

**Issue by CANIS-NAU** [DiscoverCCRI/portal_v1#29]
This would be a button that when clicked would set up a user as a PI on DISCOVER and would autofill the repository link with a specific test repository and would ask them to provide a link to a space where results could be uploaded. 

When the user goes through this special workflow, there would be additional documentation and hand-holding provided to explicitly explain each step of the workflow.

**Comment by nhatlinh300401** [comment]
Link to Experiment tutorial in the Documentation
