### ISSUE TITLE
Evaluate resource definitions

### ISSUE THREAD

**Issue by BaileyMcCauslin** [DiscoverCCRI/portal_v1#32]
The step "New Experiment Resource Definition" need to be evaluated and modified as needed. The section Definition need to be modified to other formats (JSON format currently), which is more accessible and easy-to-use.

![image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/f019cf4f-89b2-4d82-8ab8-22f91e007269)

**Comment by nhatlinh300401** [comment]
For the definition, I think we could change to the listing format (image attached below).

![image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/7962caee-6cc3-4778-9d21-1ff6fba05250)
