### ISSUE TITLE
Create a revamped resource definition

### ISSUE THREAD

**Issue by BaileyMcCauslin** [DiscoverCCRI/portal_v1#34]
Drop down for hardware type, select menu for capabilities(can select multiple) based on resource type, and text box(s) for dependencies.

**Comment by nhatlinh300401** [comment]
Hi @BaileyMcCauslin , I was absent from the meeting today, I have a question that does this relate to the resource creation process or experiment resource definition process?

**Comment by BaileyMcCauslin** [comment]
It is the experiment resource definition process. It will just make the process easier for the user by taking the json formatted string out of the equation so they can just worry about finding the resource they want.
