### ISSUE TITLE
Cloud Storage Link Update button Remnant

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#35]
Check out the screenshot of the experiment screen. Notice the update button highlighted in red at the bottom. Do we want to remove this? If we want to keep it, the update button should be positioned near the cloud storage link field.

![Screenshot 2023-06-21 at 10 46 42 AM](https://github.com/DiscoverCCRI/portal_v1/assets/60525503/e1adbb9a-245a-4a24-b59b-79d43dfb433e)

**Comment by 17jhagan** [comment]
Let's make the Update button dependent on the Mode that the experiment is in. The user should not be able to update the cloud storage link when the mode is set to "Testbed".

**Comment by nhatlinh300401** [comment]
Don't merge it yet, I need to review the styling and relocation the button "Update Link" as well.

**Comment by nhatlinh300401** [comment]
Reopened it and pushed new PR to fix the error
