### ISSUE TITLE
When Emails are sent from our portal, the formatting should be consistent throughout.

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#36]
After pulling in PR #31, I noticed there are still formatting issues throughout the experimenter workflow. For example:

1. When starting up a new experiment (notice the Aerpaw reference):
![Screenshot 2023-06-21 at 10 46 24 AM](https://github.com/DiscoverCCRI/portal_v1/assets/60525503/6d7b33f2-f7d7-45f4-a77c-a4cbe957d2df)

2. When sending Operator comments via the "Ops actions" button:
![Screenshot 2023-06-21 at 10 50 16 AM](https://github.com/DiscoverCCRI/portal_v1/assets/60525503/bf1320d2-bbe1-4822-904e-465446b8e81a)

PR #31 looked like it addressed screenshot 2, but I pulled in the most recent changes to the RedHat VM and it doesn't seem to reflect the screenshot Linh sent in the PR discussion.

**Comment by nhatlinh300401** [comment]
Hey @17jhagan, I modified the email's content to Operators when users press Initiate Development (image attached). I removed the public key out the email and added the reference URL to that experiment.
![image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/9993ce97-f8e4-4034-852c-af33f2b71ad4)

**Comment by 17jhagan** [comment]
Thanks Linh, this looks good. Are these changes reflected in PR #39?
