### ISSUE TITLE
When DISCOVER Users explore the available resources, the "Create New Resource" button should not appear.

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#44]
The "Create New Resource" button should only be available to resource managers. Currently, the "Create New Resource" button will prompt a logout page if the user is not a resource manager. The button should be hidden for all non-resource manager users.

**Comment by nhatlinh300401** [comment]
Hi @17jhagan , currently, when the user is not a resource manager, the button `Create New Resource` will be hidden from that user. In my test, I turn off the role Resource Manager in User Management (image below) and then the button `Create New Resource` is automatically hidden from my screen. Can you check that please?

![image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/ab727e8b-407d-49bf-8d7f-4148e5a59cec)

**Comment by 17jhagan** [comment]
Hey @nhatlinh300401, the current version that is on discover-dev.rc.nau.edu and the siccs workstation both show the "Create New Resource", even though I am not a resource manager. I toggled my permissions with the `/admin` Django interface. Here's how it looks on my end:

<img width="992" alt="Screenshot 2023-08-01 at 9 51 33 AM" src="https://github.com/DiscoverCCRI/portal_v1/assets/60525503/13f3ae7e-f10c-4b9e-a679-a34551e55c1f">

<img width="1303" alt="Screenshot 2023-08-01 at 9 51 50 AM" src="https://github.com/DiscoverCCRI/portal_v1/assets/60525503/b127bb7b-b11b-4665-ba33-b62706e0dc3f">

When I click on the "Create New Resource" without the "Resource Manager" role:
<img width="1020" alt="Screenshot 2023-08-01 at 9 52 11 AM" src="https://github.com/DiscoverCCRI/portal_v1/assets/60525503/56bc52cd-d36e-4f56-8138-9d71fd3c15d0">

**Comment by nhatlinh300401** [comment]
Hi Jacob, I just checked my account on [live portal](https://discover-dev.rc.nau.edu/) and my role is only Discover user. The button `Create New Resource` doesn't show up.

I have a question: do you use the same email address to login into portal and `/admin` Django interface? Since we setup the conditional to show that button which if the user is resource manager or superuser (email used to login `/admin` interface). If so, I can get rid of this one by removing the conditional with superuser.

**Comment by 17jhagan** [comment]
Ah yes, that must be my problem! I am a superuser on both the siccs workstation and the portal. Since I cannot do anything as the superuser when I do _**not**_ have the "Resource Manager" role, we should just hide it from all non-"Resource Manager" users. If the superuser wants to make changes to the resources, they can give themselves the "Resource Manager" role.
