### ISSUE TITLE
Non-Operators and Non-Resource Managers should not see Resource IP and Hostname

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#50]

**Comment by nhatlinh300401** [comment]
For this one, make sure you're not site admin, operator or resource manager. Below is what it looks like in my just Discover user account

![Image](https://github.com/DiscoverCCRI/portal_v1/assets/37945098/ceaf767a-2ece-44bd-815d-000fc66ae6a4)
