### ISSUE TITLE
Automation using R-sync between portal and remote server. 

### ISSUE THREAD

**Issue by BaileyMcCauslin** [DiscoverCCRI/portal_v1#55]
Transfer experiment data between portal and remote server where experiments are ran.  Operator approves the experiment and then send an email to experiment owner and rsync data to middleman server

**Comment by cjb873** [comment]
We have a new branch called cjb873/rsync, and this has some code that should allow the portal to use ssh/rsync programmatically to send data to a remote server. Once we have the remote server set up, and the portal has the keys set up with the server, we should able to close this.
